In [3]:
import pandas as pd

df = pd.read_excel("DatasetCallCenter - 2026-05-05T082442.350.xlsx")

# Conversion des dates
df["Créé le"] = pd.to_datetime(df["Créé le"])
df["Date de Clôture"] = pd.to_datetime(df["Date de Clôture"])

# Création du DMT (durée de traitement)
df["DMT"] = df["Date de Clôture"] - df["Créé le"]

In [31]:
df

,Titre demande,Numéro de l’incident,Créé le,Créé par,Priorité,Site,Distributeur,Espace Service,File d'attente,Client,Numéro objet d'intéraction,Statut,Date de Clôture,DMT,Jour,Heure,Mois
0,Réclamations | Réclamations Moov Money | Récla...,CAS-2752283-B4V6S0,2026-05-05 08:23:24,GUIBALE ANGE STEPHANE,Normale,Call Center,NaN,NaN,NaN,CLIENT NON IDENTIFIE,161822989,Actif,2026-05-05 08:23:29,0 days 00:00:05,Tuesday,8,5
1,Réclamations | Réclamations FTTH | Absence de ...,CAS-2752271-H6D3R8,2026-05-05 08:21:22,TAPE AMA HELENE,Normale,Call Center,NaN,NaN,CC 2ème Ligne,GLWADYS MARINA N'GUESSAN,2150058947,Actif,2026-05-05 08:22:20,0 days 00:00:58,Tuesday,8,5
2,Réclamations | Réclamations FTTH | Absence de ...,CAS-2752266-P2D3M1,2026-05-05 08:20:40,DJEDJE DENISE ANGYBELLE,Normale,Call Center,NaN,NaN,CC 2ème Ligne,AKE NIAMBA JEAN KOUADIO,2120807648,Actif,2026-05-05 08:21:24,0 days 00:00:44,Tuesday,8,5
3,Réclamations | Réclamations Moov Money | Récla...,CAS-2752264-N0F7Q5,2026-05-05 08:20:02,GUIBALE ANGE STEPHANE,Normale,Call Center,NaN,NaN,NaN,KOUAME KOUAKOU STEPHANE FRANCELIN,150566447,Actif,2026-05-05 08:20:02,0 days 00:00:00,Tuesday,8,5
4,Réclamations | Réclamations FTTH | Absence de ...,CAS-2752257-C3Q2K6,2026-05-05 08:18:53,AHIPO EPOUSE BEUGRE LAGAH MARIE-ANGE,Normale,Call Center,NaN,NaN,CC 2ème Ligne,CLIENT NON IDENTIFIE,2150054350,Actif,2026-05-05 08:19:15,0 days 00:00:22,Tuesday,8,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2282,Réclamations | Autres Réclamations | Réclamati...,CAS-2323805-V2N9M1,2026-01-06 09:21:41,YAO SENY MARIE MARTHE ESTHER,Haute,Call Center,NaN,NaN,Assistant Clientèle Entreprises,COULIBALI KARIM,142571084,Actif,2026-01-06 15:05:03,0 days 05:43:22,Tuesday,9,1
2283,Réclamations | Réclamations sur les services D...,CAS-2318071-Q6L6B4,2026-01-03 19:40:39,VONAN TAHNY-LOU MAMOH DORIS,Normale,Call Center,NaN,NaN,Assistant Clientèle Entreprises,ATTUOMAN AHOU DANIELLE MONIQUE,170086465,Actif,2026-01-05 10:49:33,1 days 15:08:54,Saturday,19,1
2284,Réclamations | Réclamations sur les services D...,CAS-2318024-S2J0H8,2026-01-03 19:13:10,KOUADIO ZIGUI AMOIN LEONCE THERESE EVODIE,Normale,Call Center,NaN,NaN,Assistant Clientèle Entreprises,YAO DJA EMMANUEL,140818658,Actif,2026-01-05 10:53:03,1 days 15:39:53,Saturday,19,1
2285,Réclamations | Contestations crédit et réclama...,CAS-2313920-G1Q0S5,2026-01-02 11:11:03,TRAORE AMOIN GRÂCE EMAMMANUELLE ANDREA,Normale,Call Center,NaN,NaN,Assistant Clientèle Entreprises,GBAMBLE LOU IRIENAN ODETTE,103728292,Actif,2026-01-06 12:23:39,4 days 01:12:36,Friday,11,1
2286,Réclamations | Contestations crédit et réclama...,CAS-2312459-L3G5L7,2026-01-01 11:58:34,NIAMIEN TAHIA ALEXANDRINE,Normale,Call Center,NaN,NaN,Assistant Clientèle Entreprises,NAHOUA BAKARY TUO,142415705,Actif,2026-01-02 12:05:11,1 days 00:06:37,Thursday,11,1

# Feature engineering

In [4]:
df["Jour"] = df["Créé le"].dt.day_name()
df["Heure"] = df["Créé le"].dt.hour
df["Mois"] = df["Créé le"].dt.month
df

,Titre demande,Numéro de l’incident,Créé le,Créé par,Priorité,Site,Distributeur,Espace Service,File d'attente,Client,Numéro objet d'intéraction,Statut,Date de Clôture,DMT,Jour,Heure,Mois
0,Réclamations | Réclamations Moov Money | Récla...,CAS-2752283-B4V6S0,2026-05-05 08:23:24,GUIBALE ANGE STEPHANE,Normale,Call Center,NaN,NaN,NaN,CLIENT NON IDENTIFIE,161822989,Actif,2026-05-05 08:23:29,0 days 00:00:05,Tuesday,8,5
1,Réclamations | Réclamations FTTH | Absence de ...,CAS-2752271-H6D3R8,2026-05-05 08:21:22,TAPE AMA HELENE,Normale,Call Center,NaN,NaN,CC 2ème Ligne,GLWADYS MARINA N'GUESSAN,2150058947,Actif,2026-05-05 08:22:20,0 days 00:00:58,Tuesday,8,5
2,Réclamations | Réclamations FTTH | Absence de ...,CAS-2752266-P2D3M1,2026-05-05 08:20:40,DJEDJE DENISE ANGYBELLE,Normale,Call Center,NaN,NaN,CC 2ème Ligne,AKE NIAMBA JEAN KOUADIO,2120807648,Actif,2026-05-05 08:21:24,0 days 00:00:44,Tuesday,8,5
3,Réclamations | Réclamations Moov Money | Récla...,CAS-2752264-N0F7Q5,2026-05-05 08:20:02,GUIBALE ANGE STEPHANE,Normale,Call Center,NaN,NaN,NaN,KOUAME KOUAKOU STEPHANE FRANCELIN,150566447,Actif,2026-05-05 08:20:02,0 days 00:00:00,Tuesday,8,5
4,Réclamations | Réclamations FTTH | Absence de ...,CAS-2752257-C3Q2K6,2026-05-05 08:18:53,AHIPO EPOUSE BEUGRE LAGAH MARIE-ANGE,Normale,Call Center,NaN,NaN,CC 2ème Ligne,CLIENT NON IDENTIFIE,2150054350,Actif,2026-05-05 08:19:15,0 days 00:00:22,Tuesday,8,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2282,Réclamations | Autres Réclamations | Réclamati...,CAS-2323805-V2N9M1,2026-01-06 09:21:41,YAO SENY MARIE MARTHE ESTHER,Haute,Call Center,NaN,NaN,Assistant Clientèle Entreprises,COULIBALI KARIM,142571084,Actif,2026-01-06 15:05:03,0 days 05:43:22,Tuesday,9,1
2283,Réclamations | Réclamations sur les services D...,CAS-2318071-Q6L6B4,2026-01-03 19:40:39,VONAN TAHNY-LOU MAMOH DORIS,Normale,Call Center,NaN,NaN,Assistant Clientèle Entreprises,ATTUOMAN AHOU DANIELLE MONIQUE,170086465,Actif,2026-01-05 10:49:33,1 days 15:08:54,Saturday,19,1
2284,Réclamations | Réclamations sur les services D...,CAS-2318024-S2J0H8,2026-01-03 19:13:10,KOUADIO ZIGUI AMOIN LEONCE THERESE EVODIE,Normale,Call Center,NaN,NaN,Assistant Clientèle Entreprises,YAO DJA EMMANUEL,140818658,Actif,2026-01-05 10:53:03,1 days 15:39:53,Saturday,19,1
2285,Réclamations | Contestations crédit et réclama...,CAS-2313920-G1Q0S5,2026-01-02 11:11:03,TRAORE AMOIN GRÂCE EMAMMANUELLE ANDREA,Normale,Call Center,NaN,NaN,Assistant Clientèle Entreprises,GBAMBLE LOU IRIENAN ODETTE,103728292,Actif,2026-01-06 12:23:39,4 days 01:12:36,Friday,11,1
2286,Réclamations | Contestations crédit et réclama...,CAS-2312459-L3G5L7,2026-01-01 11:58:34,NIAMIEN TAHIA ALEXANDRINE,Normale,Call Center,NaN,NaN,Assistant Clientèle Entreprises,NAHOUA BAKARY TUO,142415705,Actif,2026-01-02 12:05:11,1 days 00:06:37,Thursday,11,1

# ANALYSES CLÉS

In [5]:
print(df["DMT"].describe())

count                         2287
mean     0 days 20:54:28.532575426
std      2 days 12:26:44.202349822
min                0 days 00:00:00
25%                0 days 00:00:49
50%                0 days 00:31:54
75%                0 days 20:36:56
max               44 days 05:26:14
Name: DMT, dtype: object

# DMT par priorité

In [6]:
dmt_priorite = df.groupby("Priorité")["DMT"].mean().sort_values()
print(dmt_priorite)

Priorité
Faible              0 days 00:00:01
Haute     0 days 19:36:57.401606425
Normale   0 days 21:04:34.030436917
Name: DMT, dtype: timedelta64[ns]

# DMT par file d’attente

In [7]:
dmt_file = df.groupby("File d'attente")["DMT"].mean().sort_values(ascending=False)
print(dmt_file)

File d'attente
Assistant Clientèle Entreprises      4 days 06:05:24.375000
CC 2ème Ligne                     1 days 09:22:28.643835616
Support SAV                       0 days 14:43:11.326923076
Assistant BO Réclamations         0 days 13:19:04.466080402
Conseiller Client                 0 days 11:15:12.531914893
1ère ligne DT                     0 days 02:59:26.508403361
Name: DMT, dtype: timedelta64[ns]

# Volume de tickets

In [8]:
volume = df["Créé le"].dt.date.value_counts().sort_index()
print(volume)

Créé le
2026-01-01      1
2026-01-02      1
2026-01-03      2
2026-01-06      1
2026-01-08      3
             ...
2026-05-01    239
2026-05-02    287
2026-05-03    106
2026-05-04    421
2026-05-05     32
Name: count, Length: 107, dtype: int64

# Performance agents

In [9]:
perf_agents = df["Créé par"].value_counts()
print(perf_agents)

Créé par
COUBA ZITA DALLY                        117
GOURE VALERIE NAN KAREN                  70
ADJE MARLYNE GNIMA                       66
KOFFI GILLES ANICET YAYO                 62
AHIPO EPOUSE BEUGRE LAGAH MARIE-ANGE     54
                                       ...
APE KOKO MIREILLE                         1
ASSIELIE BADJO LUCIE-AIMEE                1
SERY BENEDICTE CLARA                      1
AMOUSSOU SIMONE                           1
NIAMIEN TAHIA ALEXANDRINE                 1
Name: count, Length: 91, dtype: int64

# MACHINE LEARNING

## Prédire le DMT

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

# Sélection de features simples
X = df[["Priorité"]]
X = pd.get_dummies(X)

y = df["DMT"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestRegressor()
model.fit(X_train, y_train)

print("Score:", model.score(X_test, y_test))

Score: -0.0016349674301927575